import Head from "next/head";
import styled from "styled-components";
import { useState } from "react";
import CreateFlowForm from "/components/CreateFlowForm";
import { nanoid } from "nanoid";
import FlowCard from "/components/FlowCard";
import useLocalStorage from "/hooks/useLocalStorage";
import { flowDummys } from "/db";

import { getAllFlows } from "/services/flowService";

export async function getServerSideProps() {
  const flowsDB = await getAllFlows();
  return {
    props: { flowsDB: flowsDB },
  };
}

export default function Home({ flowsDB }) {
  const [openForm, setOpenForm] = useState(false);
  const [editFormId, setEditFormId] = useState(null);
  // const [flows, setFlows] = useLocalStorage("flows", flowDummys);
  //const [flows, setFlows] = useState(flowsDB);

  console.log(flowsDB);
  console.log(editFormId);
  function toggleOpenForm() {
    setOpenForm((prev) => !prev);
  }

  async function handleFlowPost(flowData) {
    try {
      const response = await fetch("/api/flows", {
        method: "POST",
        body: JSON.stringify(flowData),
      });

      const result = await response.json();
      console.log(result);
      if (result.createdId) {
        alert("Flow has been created");
      } else {
        alert("Creating a flow did not work!!");
      }
    } catch (error) {
      console.error(error);
    }
    setOpenForm(false);
  }

  async function handleFlowUpdate(flowData) {
    try {
      const response = await fetch("/api/flows", {
        method: "PUT",
        body: JSON.stringify(flowData),
      });

      const result = await response.json();
      console.log(result.name);
      if (result.name) {
        alert("Flow has been updated");
      } else {
        alert("Updating a flow did not work!!");
      }
    } catch (error) {
      console.error(error);
    }
    setOpenForm(false);
    setEditFormId(null);
  }

  async function handleDelete(id) {
    try {
      const response = await fetch(`/api/flows`, {
        method: "DELETE",
        body: JSON.stringify(id),
      });
      console.log(response);
      const result = await response.json();

      if (result.id) {
        alert("Flow has been deleted");
      } else {
        alert("Deleting a flow did not work!!");
      }
    } catch (error) {
      console.error(error);
    }
  }

  /*  function addFlow(name, hours, minutes) {
    setFlows([
      ...flows,
      {
        id: nanoid(),
        name: name,
        duration: {
          hours: hours,
          minutes: minutes,
        },
        asanas: [],
      },
    ]);
    setOpenForm(false);
  } */

  /*  function deleteFlow(flowCardId) {
    setFlows(flows.filter((flow) => flow.id !== flowCardId));
  }
 */
  /* function editFlowBasicData(
    updatedName,
    updatedHours,
    updatedMinutes,
    cardId
  ) {
    setFlows(
      flows.map((flow) =>
        flow.id === cardId
          ? {
              ...flow,
              name: updatedName,
              duration: { hours: updatedHours, minutes: updatedMinutes },
            }
          : flow
      )
    );
    setEditFormId(null);
  } */

  function cancelEditFlow() {
    setEditFormId(null);
  }

  function closeForm() {
    setOpenForm(false);
  }

  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <StyledH2>Let&apos;s flow</StyledH2>

        {flowsDB.map((flow) => (
          <FlowCard
            key={flow.id}
            name={flow.name}
            hours={flow.hours}
            minutes={flow.minutes}
            id={flow.id}
            deleteFlow={() => handleDelete(flow.id)}
            setEditFormId={() => setEditFormId(flow.id)}
          />
        ))}
        {openForm && (
          <CreateFlowForm
            flows={flowsDB}
            // addFlow={addFlow}
            handleFlowPost={handleFlowPost}
            closeForm={closeForm}
          />
        )}
        {editFormId != null &&
          flowsDB.map(
            (flow) =>
              flow.id === editFormId && (
                <CreateFlowForm
                  key={flow.id}
                  flows={flowsDB}
                  id={flow.id}
                  editFormId={editFormId}
                  defaultName={flow.name}
                  defaultHours={flow.hours}
                  defaultMinutes={flow.minutes}
                  handleFlowUpdate={handleFlowUpdate}
                  /* editFlowBasicData={(
                    updatedName,
                    updatedHours,
                    updatedMinutes
                  ) =>
                    editFlowBasicData(
                      updatedName,
                      updatedHours,
                      updatedMinutes,
                      flow.id
                    )
                  } */
                  cancelEditFlow={cancelEditFlow}
                />
              )
          )}
        <StyledAddButton onClick={toggleOpenForm}>
          {openForm ? "x" : "+"}
        </StyledAddButton>
      </main>
    </div>
  );
}

const StyledAddButton = styled.button`
  position: fixed;
  bottom: 1.5rem;
  right: 2rem;
  z-index: 30;
  border: none;
  display: block;
  margin: auto;
  background: var(--highlight-gradient);
  box-shadow: var(--drop-shadow-gray);
  color: var(--text-light);
  font-size: 1.5rem;
  width: 3.5rem;
  height: 3.5rem;
  border-radius: 50%;
  text-align: center;
  cursor: pointer;
  &:active {
    background-color: var(--highlight);
    color: var(--text-light);
  }
`;

const StyledH2 = styled.h2`
  font-size: 2rem;
`;
