import Head from "next/head";
import styled from "styled-components";
import AsanaCard from "../components/Asana-Card/AsanaCard";
import asanas from "../db";
import SearchBar from "../components/SearchBar";

export default function Home({ searchQuery, setSearchQuery }) {
  console.log(searchQuery);

  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Your Daily Flow</h1>
        <SearchBar setSearchQuery={setSearchQuery} />
        <StyledList>
          {asanas.map((asana) => {
            const nameInLowerCase = asana.english_name.toLowerCase();
            const searchQueryInLowerCase = searchQuery.toLowerCase();
            if (nameInLowerCase.includes(searchQueryInLowerCase)) {
              return (
                <li key={asana.id}>
                  <AsanaCard
                    name={asana.english_name}
                    img={asana.img_url}
                    id={asana.id}
                    showDeleteButton={false}
                  />
                </li>
              );
            }
          })}
        </StyledList>
      </main>
    </div>
  );
}

const StyledList = styled.ul`
  list-style: none;
`;
